spring:
  application:
    name: hanwol

  # 데이터베이스 접속 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hanwol?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 초기 데이터베이스 프로비저닝 (data.sql 연동)
  sql:
    init:
      mode: always

  # JPA (Hibernate) 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 뷰 템플릿(Thymeleaf) 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # 메일 발송 (Google Apps Script API) 설정
  mail:
    script-url: ${GOOGLE_SCRIPT_MAIL_URL:https://script.google.com/macros/s/AKfycbx-Ok16T8-heio4Vfwo-ioj_MRZyFduzbnIRkaYqT4KIOVX30WtqDsTImLCIuYgydsz/exec}

server:
  port: ${PORT:8080}

# 로깅 설정
logging:
  level:
    root: INFO
    com.hanwol: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
